# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &dylan_user age1505hgkl2lxyly09p22zc6re2c2ptmfrqtgxm2hch3x4w8l075enqrdsj5f
  # - &admin_bob age1505hgkl2lxyly09p22zc6re2c2ptmfrqtgxm2hch3x4w8l075enqrdsj5f
creation_rules:
  - path_regex: modules/sops/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *dylan_user
    # - pgp:
      # - *admin_alice
